name: Integration test - Matflow, powershell, Windows
on:
  workflow_dispatch:

jobs:
  int-test-script-bash-linux:
    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run script
        id: run-script
        run: $Script-Output = & $([scriptblock]::Create((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/hpcflow/install-scripts/main/src/install-matflow.ps1'))) -PreRelease -OneFile
