name: Integration test - MatFlow, powershell, Windows

env:
  APP_NAME: "matflow"
  INSTALL_ROOT: "${env:USERPROFILE}\\AppData\\Local\\matflow"

on:
  workflow_dispatch:

jobs:
  int-test-script-powershell-windows:
    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run script
        id: run-script
        run: |
          $ScriptOutput = & $([scriptblock]::Create((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/hpcflow/install-scripts/feat/gha-int-test-all/src/install-matflow.ps1'))) -PreRelease -OneFile 6>&1
          $ScriptOutputSplit = $ScriptOutput -Split " "
          Write-Host $ScriptOutputSplit[15]


      - name: Check results
        run: |
          $app_path = "${{ env.INSTALL_ROOT }}\\matflow-v0.3.0a36-win.exe test"
          Invoke-Expression -Command $app_path

      
