name: Integration test - HPCFlow, powershell, Windows

env:
  APP_NAME: "matflow"
  INSTALL_ROOT: "${env:USERPROFILE}\\AppData\\Local\\matflow"

on:
  workflow_dispatch:  
  pull_request:
    types: [opened, edited, synchronize]
    branches: [main, develop]

jobs:
  int-test-script-powershell-windows:
    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run script
        id: run-script
        run: |
          $ScriptOutput = & $([scriptblock]::Create((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/hpcflow/install-scripts/main/src/install-hpc.ps1'))) -PreRelease -OneFile 6>&1
          $ScriptOutputSplit = $ScriptOutput -Split " "
          $artifact_name = $ScriptOutputSplit[15]
          echo "ART_NAME=$artifact_name" >> $env:GITHUB_ENV


      - name: Check results
        run: |
          $app_path = "${{ env.INSTALL_ROOT }}\\${{ env.ART_NAME }} test"
          Invoke-Expression -Command $app_path