name: Integration test - Matflow, BASH, macos
on:
  workflow_dispatch:

jobs:
  int-test-script-bash-linux:
    runs-on: macos-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run script
        id: run-script
        run: |
          script_output=`(touch tmp.sh && curl -fsSL https://raw.githubusercontent.com/hpcflow/install-scripts/main/src/install-matflow.sh > tmp.sh && bash tmp.sh --prerelease --path --onefile) ; rm tmp.sh`
          artifact_name=`echo $script_output | grep matflow- | cut -d " " -f 30`
          echo "art_name=$artifact_name" >> $GITHUB_ENV
          echo `ls ~/Library/Application\ Support/matflow`

      - name: Run Matflow test suite
        run: |
          artifact_name=${{ env.art_name }}
          ~/Library/Application\ Support/hpcflow/$artifact_name test