name: Integration test - HPCFlow, BASH, Linux

env:
  APP_NAME: "hpcflow"
  INSTALL_ROOT: "~/.local/share"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, synchronize]
    branches: [main, develop]

jobs:
  get-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Get and store current branch name
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo $branch_name
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
          echo ${{ env.BRANCH_NAME }}

  int-test-script-bash-linux-default:
    needs: get-branch-name
    runs-on: ubuntu-latest

    steps:

      - name: Run script
        run: |
          echo ${{ env.BRANCH_NAME }}
          script_output=`(touch tmp.sh && curl -fsSL https://raw.githubusercontent.com/hpcflow/install-scripts/${{ env.BRANCH_NAME }}/src/install-hpcflow.sh > tmp.sh && bash tmp.sh --prerelease --path --onefile) ; rm tmp.sh`
          artifact_name=`echo $script_output | grep hpcflow- | cut -d " " -f 30`
          echo "ART_NAME=$artifact_name" >> $GITHUB_ENV

      - name: Run HPCFlow test suite
        run: |
          ${{ env.INSTALL_ROOT }}/${{ env.APP_NAME }}/links/${{ env.ART_NAME }} test

      - name: Cleanup
        run: rm -r ${{ env.INSTALL_ROOT }}/${{ env.APP_NAME }}

  int-test-script-bash-linux-prerelease-univlink:
    needs: get-branch-name
    runs-on: ubuntu-latest

    steps:

      - name: Run script
        run: |
          script_output=`(touch tmp.sh && curl -fsSL https://raw.githubusercontent.com/hpcflow/install-scripts/${{ env.BRANCH_NAME }}/src/install-hpcflow.sh > tmp.sh && bash tmp.sh --prerelease --path --onefile --univlink) ; rm tmp.sh`
          echo "ART_NAME_UNIV=hpcflow-dev" >> $GITHUB_ENV

      - name: Run HPCFlow test suite
        run: |
          ${{ env.INSTALL_ROOT }}/${{ env.APP_NAME }}/links/${{ env.ART_NAME_UNIV }} test

      - name: Cleanup
        run: rm -r ${{ env.INSTALL_ROOT }}/${{ env.APP_NAME }}